platform :ios, '9.0'
use_frameworks!

target 'LUMVP' do
pod 'pop'
#pod 'YTKNetwork'
pod 'PPNetworkHelper'
pod 'TABAnimated'
pod 'MJExtension'
pod 'Masonry'
#pod 'Lumvp',:path => 'Lumvp.podspec'
pod 'Graver'
end

target 'Swift' do
    pod 'SnapKit'
end
