platform :ios, '9.0'
use_frameworks!

target 'LUMVP' do
pod 'pop'
pod 'PPNetworkHelper'
pod 'TABAnimated'
pod 'MJExtension'
pod 'Masonry'
pod 'Graver'
pod 'info'
pod 'MUKit/popupView'
pod 'MUKit/ImageCache'
pod 'ChameleonFramework'
pod 'MJRefresh'
pod 'WoodPeckeriOS', :configurations => ['Debug']
end

target 'Swift' do
    pod 'SnapKit'
end
